.TH debathena-printing.conf 5 Debathena "July 2008" "Athena Printing"
.SH NAME
debathena-printing.conf \- specify preferences for printing on Athena
.SH DESCRIPTION
Debathena supports two printing systems: LPRng, the current Athena printing
architecture, and CUPS, a system with better cross-platform support slated for
use in Athena 10.
.PP
The Debathena-provided 
.BR lpr (1),
.BR lpq (1),
.BR lprm (1),
.BR lpc (8),
.BR lp (1),
and
.BR cancel (1)
scripts attempt to 
intelligently determine whether the CUPS or the LPRng queue was intended, but
if they can not decide or if there is a conflict, the file
/etc/debathena-printing.conf specifies which mechanism should be preferred.
.PP
The debathena-printing.conf file should contain either the word "cups" or the
word "lprng". If the file does not exist or contains neither of those two
strings, all printing will prefer CUPS over LPRng.
.SH AUTHOR
Evan Broder, SIPB Debathena <debathena@mit.edu>.
.SH SEE ALSO
.BR lpr (1),
.BR lpq (1),
.BR lprm (1),
.BR lpc (8),
.BR lp (1),
.BR cancel (1)
