.TH lpq 1 Debathena "March 2013" "Athena Printing"
.SH NAME
lpq \- show Athena printer queue status
.SH SYNOPSIS
.B lpq
.RB [ \-P printer]
[other options]
.SH DESCRIPTION
This wrapper provides support for Hesiod and MIT's load-balancing
environment in order to execute the cups-lpq(1) command with the correct
environment and arguments.

This wrapper no longer has support for LPRng or traditional LPD queues.
To query an LPD printer, you should ask your workstation
administrator to add it as a local print queue, or use the rlpq(1)
program.
.PP
See the
.BR cups-lpq (1)
man page for the CUPS version of lpq.
.SH OPTIONS
.TP
.BR \-P printer
Specifies the printer to use, which determines which lpq version to use. If not specified, it will default to the value of the PRINTER environment variable.
.PP
All other options are passed on to the final lpq command.
.SH AUTHOR
Evan Broder, SIPB Debathena <debathena@mit.edu>.
.br
Jonathan Reed, Massachusetts Institute of Technology
.SH SEE ALSO
.BR rlpq(1),
.BR cups-lpq (1)
