.TH lpr 1 Debathena "March 2013" "Athena Printing"
.SH NAME
lpr \- print to Athena printers
.SH SYNOPSIS
.B lpr
.RB [ \-P printer]
[other options] [filename]
.SH DESCRIPTION
This wrapper provides support for Hesiod and MIT's load-balancing
environment in order to execute the cups-lpr(1) command with the correct
environment and arguments.

This wrapper no longer has support for LPRng or traditional LPD queues.
To print to an LPD printer, you should ask your workstation
administrator to add it as a local print queue, or use the rlpr(1)
program.
.PP
See the
.BR cups-lpr (1)
man page for the CUPS version of lpr.
.PP
See also the
.B COMMON JOB OPTIONS
section of the
.BR cups-lp (1)
man page for a description of the
.RB -o
options available to
.BR cups-lpr (1)
for, e.g., double-sided printing.
.SH OPTIONS
.TP
.BR \-P printer
Specifies the printer to use, which determines which lpr version to use. If not specified, it will default to the value of the PRINTER environment variable.
.PP
All other options are passed on to the final lpr command.
.SH AUTHOR
Evan Broder, SIPB Debathena <debathena@mit.edu>.
.br
Jonathan Reed, Massachusetts Institute of Technology
.SH SEE ALSO
.BR rlpr (1),
.BR cups-lpr (1)
