.TH lpr 1 Debathena "November 2009" "Athena Printing"
.SH NAME
lpr \- print to Athena printers
.SH SYNOPSIS
.B lpr
.RB [ \-P printer]
[other options] [filename]
.SH DESCRIPTION
Debathena supports two printing systems: the traditional LPRng and the
newer CUPS with better cross-platform support. This command is a script
which detects if you are printing to an LPRng or CUPS print queue and runs
the appropriate version of lpr.
.PP
See the
.BR mit-lpr (1)
man page for the LPRng version of lpr, or the
.BR cups-lpr (1)
man page for the CUPS version of lpr.
.PP
See also the
.B COMMON JOB OPTIONS
section of the
.BR cups-lp (1)
man page for a description of the
.RB -o
options available to
.BR cups-lpr (1)
for, e.g., double-sided printing.
.SH OPTIONS
.TP
.BR \-P printer
Specifies the printer to use, which determines which lpr version to use. If not specified, it will default to the value of the PRINTER environment variable.
.PP
All other options are passed on to the final lpr command.
.SH AUTHOR
Evan Broder, SIPB Debathena <debathena@mit.edu>.
.SH SEE ALSO
.BR mit-lpr (1),
.BR cups-lpr (1)
