.TH lprm 1 Debathena "March 2013" "Athena Printing"
.SH NAME
lprm \- remove jobs from Athena printers
.SH SYNOPSIS
.B lprm
.RB [ \-P printer]
[other options]
.SH DESCRIPTION
This wrapper provides support for Hesiod and MIT's load-balancing
environment in order to execute the cups-lprm(1) command with the correct
environment and arguments.

This wrapper no longer has support for LPRng or traditional LPD queues.
To remove jobs from an LPD printer, you should ask your workstation
administrator to add it as a local print queue, or use the rlprm(1)
program.
.PP
See the
.BR cups-lprm (1)
man page for the CUPS version of lprm.
.SH OPTIONS
.TP
.BR \-P printer
Specifies the printer to use, which determines which lprm version to use. If not specified, it will default to the value of the PRINTER environment variable.
.PP
All other options are passed on to the final lprm command.
.SH AUTHOR
Evan Broder, SIPB Debathena <debathena@mit.edu>.
.br
Jonathan Reed, Massachusetts Institute of Technology
.SH SEE ALSO
.BR rlprm (1),
.BR cups-lprm (1)
