.TH lprm 1 Debathena "November 2009" "Athena Printing"
.SH NAME
lprm \- remove jobs from Athena printers
.SH SYNOPSIS
.B lprm
.RB [ \-P printer]
[other options]
.SH DESCRIPTION
Debathena supports two printing systems: the traditional LPRng and the
newer CUPS with better cross-platform support. This command is a script
which detects if you are printing to an LPRng or CUPS print queue and runs
the appropriate version of lprm.
.PP
See the
.BR mit-lprm (1)
man page for the LPRng version of lprm, or the
.BR cups-lprm (1)
man page for the CUPS version of lprm.
.SH OPTIONS
.TP
.BR \-P printer
Specifies the printer to use, which determines which lprm version to use. If not specified, it will default to the value of the PRINTER environment variable.
.PP
All other options are passed on to the final lprm command.
.SH FILES
/etc/debathena-printing.conf
.SH AUTHOR
Evan Broder, SIPB Debathena <debathena@mit.edu>.
.SH SEE ALSO
.BR mit-lprm (1),
.BR cups-lprm (1),
.BR debathena-printing.conf (5)
